name: flutter_markup_text
description: This powerful Flutter package empowers developers to annotate their text with markup tags, allowing for the extraction and association of valuable information.
version: 0.0.2
homepage: https://github.com/real-ali/markup_text

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

